vim.cmd("source $HOME/.config/nvim/lua/init.vim")
require("plugin")
require("keybindings")
require("plugin-config.nvim_tree")
require("plugin-config.lualine")
require("plugin-config.gruvbox")
require("plugin-config.mason")
require("plugin-config.nvim_lspconfig")
require("plugin-config.nvim_treesitter")
require("plugin-config.none_ls")
require("plugin-config.nvim_cmp")
require("plugin-config.comment")
require("plugin-config.lspsaga")
require("plugin-config.telescope")
require("plugin-config.gitsigns")
require("plugin-config.toggleterm")
require("plugin-config.copilot")
require("plugin-config.fidget")
